### ISSUE TITLE
Dr. Memory does not compile on Ubuntu 19.10 with gcc 9.2.1

### ISSUE THREAD

**Issue by thbtppl** [DynamoRIO/drmemory#2244]
Hello, this is most likely linked to [https://github.com/DynamoRIO/dynamorio/issues/3917](https://github.com/DynamoRIO/dynamorio/issues/3917)

I cannot compile Dr Memory from source (master branch downloaded yesterday). Using ccmake, I set `CMAKE_BUILD_TYPE` to `Debug` and left `TOOL_DR_HEAPSTAT` set to `OFF`.

Then, the command `cmake --build .` yields

```
Scanning dependencies of target generate_syslog
[  0%] Generating ../event_strings.h
[  0%] Built target generate_syslog
Scanning dependencies of target drmemfuncs
[  1%] Building ASM object dynamorio/core/CMakeFiles/drmemfuncs.dir/arch/x86/memfuncs.asm.o
[  1%] Building C object dynamorio/core/CMakeFiles/drmemfuncs.dir/lib/memmove.c.o
In file included from /home/thibaut/Packages/drmemory/dynamorio/core/unix/os_public.h:46,
                 from /home/thibaut/Packages/drmemory/dynamorio/core/unix/os_exports.h:47,
                 from /home/thibaut/Packages/drmemory/dynamorio/core/lib/../globals.h:353,
                 from /home/thibaut/Packages/drmemory/dynamorio/core/lib/memmove.c:44:
/home/thibaut/Packages/drmemory/dynamorio/core/unix/include/sigcontext.h:20: error: "FP_XSTATE_MAGIC2_SIZE" redefined [-Werror]
   20 | #define FP_XSTATE_MAGIC2_SIZE sizeof(FP_XSTATE_MAGIC2)
      | 
In file included from /usr/include/signal.h:291,
                 from /home/thibaut/Packages/drmemory/dynamorio/core/lib/globals_shared.h:125,
                 from /home/thibaut/Packages/drmemory/dynamorio/core/lib/../globals.h:93,
                 from /home/thibaut/Packages/drmemory/dynamorio/core/lib/memmove.c:44:
/usr/include/x86_64-linux-gnu/bits/sigcontext.h:29: note: this is the location of the previous definition
   29 | #define FP_XSTATE_MAGIC2_SIZE sizeof (FP_XSTATE_MAGIC2)
      | 
cc1: all warnings being treated as errors
make[2]: *** [dynamorio/core/CMakeFiles/drmemfuncs.dir/build.make:73: dynamorio/core/CMakeFiles/drmemfuncs.dir/lib/memmove.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:475: dynamorio/core/CMakeFiles/drmemfuncs.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```
System information:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan

gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008

cmake version 3.13.4
```

(impossible to find cmake < 3.xx.x these days on that version of Ubuntu)
